{{- if .Values.jobs.restore.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-rclone-job
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  backoffLimit: {{ .Values.jobs.restore.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: rclone
          image: "{{ .Values.jobs.restore.image.repository }}:{{ .Values.jobs.restore.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -x;
              rm -rf /opt/backup/2* && \
              {{- if eq .Values.jobs.restore.type "databases" }}
              rclone copy {{ .Values.jobs.restore.providerName }}:{{ .Values.jobs.restore.bucketName }}/{{ .Values.jobs.restore.version }}/{{ .Values.jobs.restore.serverName }}/{{ .Values.jobs.restore.bench }}/{{ .Values.jobs.restore.prodSiteName }}/{{ .Values.jobs.restore.type }}/{{ .Values.jobs.restore.fileName }} /opt/backup/ --log-level DEBUG --log-file=/tmp/rclone-log.txt && \
              {{- else }}
              rclone copy {{ .Values.jobs.restore.providerName }}:{{ .Values.jobs.restore.bucketName }}/{{ .Values.jobs.restore.version }}/{{ .Values.jobs.restore.serverName }}/{{ .Values.jobs.restore.bench }}/{{ .Values.jobs.restore.prodSiteName }}/{{ .Values.jobs.restore.type }}/{{ .Values.jobs.restore.Date }}/{{ .Values.jobs.restore.fileName }} /opt/backup/ --log-level DEBUG --log-file=/tmp/rclone-log.txt && \
              {{- end }}
              ls /opt/backup
          volumeMounts:
            - name: shared-volume
              mountPath: /opt/backup
          resources: {{ .Values.jobs.restore.resources | toYaml | nindent 12 }}           
      volumes:
        - name: shared-volume
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
{{- end }}