{{- if .Values.jobs.restore.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "erpnext.fullname" . }}-restore-site-{{ now | date "20060102150405" }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.jobs.restore.backoffLimit }}
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["bash", "-c"]
          args:
            - >
              set -x;
              cd /home/frappe/frappe-bench/sites/ &&
              ls  && 
              file="{{ .Values.jobs.restore.fileName }}";
              gzip -d "$file" &&
              uncompressed="${file%.gz}";
              echo "Uncompressed file name: $uncompressed";
              ls ;
              sed 's/\sDEFINER=`[^`]*`@`[^`]*`//g' -i /home/frappe/frappe-bench/sites/$uncompressed ;
              bench --site "{{ .Values.jobs.restore.siteName }}" --force restore /home/frappe/frappe-bench/sites/$uncompressed --db-root-password {{ .Values.jobs.restore.dbRootPassword }} ;
              bench --site "{{ .Values.jobs.restore.siteName }}" migrate ;
              bench --site "{{ .Values.jobs.restore.siteName }}" enable-scheduler ;
              bench --site "{{ .Values.jobs.restore.siteName }}" execute whitelabel.cleanup.cleanup ;
              bench --site "{{ .Values.jobs.restore.siteName }}" execute nixpend_healthcare.patches.v14_10_0.create_procedure.execute ;
              rm -rf /home/frappe/frappe-bench/sites/$uncompressed ;
              bench --site "{{ .Values.jobs.restore.siteName }}" migrate ;



          volumeMounts:
            - name: sites-dir
              mountPath: /home/frappe/frappe-bench/sites
          resources:
            {{- toYaml .Values.jobs.restore.resources | nindent 12 }}
      volumes:
        - name: sites-dir
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
{{- end }}
